# Generated by Django 5.1.2 on 2024-11-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], default='pending', max_length=50),
        ),
    ]
