# Generated by Django 5.1.2 on 2024-11-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('On The Way', 'On The Way'), ('Cancel', 'Cancel'), ('Packed', 'Packed')], default='pending', max_length=50),
        ),
    ]
